# .streamlit/config.toml

[theme]
# The preset Streamlit theme that your custom theme inherits from.
# One of "light" or "dark".
base = "dark"

# Primary accent color for interactive elements.
primaryColor = "641B2E"

# Background color for the main content area.
backgroundColor = "7B4019"

# Background color for sidebar and most interactive widgets.
secondaryBackgroundColor = "FF7D29"

# Color used for almost all text.
textColor = "FFEEA9"

#2c3e50

# Font family for all text in the app, except code blocks.
# One of "sans serif", "serif", or "monospace".
font = "monospace"