# .streamlit/config.toml

[theme]
# The preset Streamlit theme that your custom theme inherits from.
# One of "light" or "dark".
base = "dark"

# Primary accent color for interactive elements.
primaryColor = "#000000"

# Background color for the main content area.
backgroundColor = "#222222"

# Background color for sidebar and most interactive widgets.
secondaryBackgroundColor = "#1DCD9F"

# Color used for almost all text.
textColor = "#169976"

#2c3e50

# Font family for all text in the app, except code blocks.
# One of "sans serif", "serif", or "monospace".
font = "monospace"